### ISSUE TITLE
go-control-plane

### ISSUE THREAD

**Issue by chopmann** [poyaz/envoy-container#1]
The go-control-plane has a bunch of stuff that makes it easy to integrate with envoy.
https://github.com/envoyproxy/go-control-plane

For some examples on how to use it:
https://github.com/datawire/ambex
https://github.com/dkfbasel/kolumbus
https://github.com/solo-io/gloo/tree/1f965929fe5669fe21a02dc6c6d3f8b7cffdd34a/projects/gloo/pkg/xds
https://medium.com/@salmaan.rashid/envoy-discovery-hello-world-d3e44d19603d

might be easier than doing the REST API on nodejs.

**Comment by poyaz** [comment]
ty very match

i see them
